# Site settings
title: Oasis of Lodo
email: james@lord-family.net
description: "Bringing a Dream to the Playa"
baseurl: ""
url: "http://jamesalord.github.io"
twitter_username: BigRedDad
github_username:  jamesalord
facebook_username:  james.lord.3

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
