# Site settings
title: The Wandering Blog
email: james@lord-family.net
description: "A blog about whatever interests me."
baseurl: ""
url: "http://jamesalord.github.io"
twitter_username: jamesalord
github_username:  jamesalord
facebook_username:  jamesalord

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
